name: github_browser
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  freezed: ^3.0.6
  build_runner: ^2.4.15
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  envied: ^1.1.1
  mockito: ^5.4.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  oauth2: ^2.0.3
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.3.1
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  envied_generator: ^1.1.1

flutter:
  uses-material-design: true
  generate: true
